# Generated by Django 3.2.6 on 2021-09-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import form.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0006_auto_20210917_1021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation_message', models.TextField(default='Your response has been recorded.', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('collect_email', models.BooleanField()),
                ('skeleton', models.TextField()),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='club.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='form.form')),
                ('responders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=15)),
                ('value', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TextResponses', to='form.response')),
            ],
        ),
        migrations.CreateModel(
            name='FileResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=15)),
                ('value', models.FileField(blank=True, upload_to='', validators=[form.models.file_size_limit])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FileResponses', to='form.form')),
            ],
        ),
    ]
