# Generated by Django 3.2.9 on 2021-12-04 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0004_auto_20211130_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='FormResponse',
        ),
    ]
