# Generated by Django 3.2.9 on 2021-12-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_response_formresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textresponse',
            old_name='question_id',
            new_name='question',
        ),
        migrations.DeleteModel(
            name='FileResponse',
        ),
    ]
