# Generated by Django 3.2.9 on 2021-12-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20211204_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=15)),
                ('value', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResponseElements', to='form.formresponse')),
            ],
        ),
        migrations.DeleteModel(
            name='TextResponse',
        ),
    ]
