# Generated by Django 3.2.9 on 2021-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20211204_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_multiple_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='closes_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
