# Generated by Django 3.2.10 on 2021-12-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20211204_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='collect_email',
            field=models.BooleanField(default=True),
        ),
    ]
