# Generated by Django 3.2.10 on 2021-12-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0029_alter_competitionwinner_position'),
        ('form', '0010_alter_form_closes_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='club.competition'),
        ),
    ]
