# Generated by Django 3.2.10 on 2021-12-30 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_form_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
