# Generated by Django 3.2.9 on 2021-11-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0002_auto_20210926_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='stage',
            field=models.CharField(choices=[('i', 'Initiation'), ('p', 'Planning'), ('e', 'Execution'), ('mc', 'Monitoring and Controlling'), ('c', 'Closure')], max_length=40),
        ),
    ]
