# Generated by Django 3.2.9 on 2021-11-10 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0003_alter_idea_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='estimate_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
    ]
