# Generated by Django 3.2.9 on 2021-11-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0004_auto_20211110_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
