# Generated by Django 3.2.9 on 2021-11-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0005_alter_idea_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='role',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='visibility',
        ),
        migrations.AddField(
            model_name='idea',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
