# Generated by Django 3.2.9 on 2021-11-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0006_auto_20211119_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='profile',
        ),
    ]
