# Generated by Django 3.2.9 on 2021-11-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0026_alter_profile_id'),
        ('ecell', '0007_remove_idea_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='owners',
            field=models.ManyToManyField(related_name='ideas', to='connect.Profile'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
