# Generated by Django 3.2.10 on 2022-02-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0031_alter_teacher_email'),
        ('ecell', '0008_auto_20211120_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarked_ideas', to='connect.Profile'),
        ),
    ]
