# Generated by Django 3.2.10 on 2022-02-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecell', '0009_idea_bookmarked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroToOneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('tnc_stage', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zero_to_one_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
