# Generated by Django 3.2.10 on 2022-02-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0010_zerotooneuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='college',
        ),
        migrations.AddField(
            model_name='idea',
            name='creation_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='social_links',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='stage',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
