# Generated by Django 3.2.10 on 2022-02-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0011_auto_20220205_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='estimate_time',
        ),
    ]
