# Generated by Django 3.2.10 on 2022-02-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0012_remove_idea_estimate_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='creation_stage',
            new_name='form_filling_stage',
        ),
        migrations.AddField(
            model_name='idea',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='idea',
            name='estimate_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
