# Generated by Django 3.2.10 on 2022-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0014_rename_idea_idea_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='estimate_time',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='join_date',
            new_name='startedOn',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='visibility',
        ),
        migrations.AddField(
            model_name='idea',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
