# Generated by Django 3.2.10 on 2022-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0031_alter_teacher_email'),
        ('ecell', '0015_auto_20220206_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_ideas', to='connect.Profile'),
        ),
    ]
