# Generated by Django 3.2.10 on 2022-02-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0016_alter_idea_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='updates',
            field=models.TextField(blank=True),
        ),
    ]
