# Generated by Django 3.2.10 on 2022-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0017_idea_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
