# Generated by Django 3.2 on 2021-05-06 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('education', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=2)),
                ('email', models.EmailField(editable=False, max_length=75)),
                ('contact', models.BigIntegerField()),
                ('handle', models.CharField(blank=True, max_length=500)),
                ('isvendor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Teacher_set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Skill_set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
