# Generated by Django 3.2.3 on 2021-05-21 08:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(blank=True, max_length=30)),
                ('Gender', models.CharField(blank=True, max_length=1)),
                ('Degree', models.CharField(blank=True, max_length=1)),
                ('Course', models.CharField(blank=True, max_length=10)),
                ('Handle', models.CharField(blank=True, max_length=50)),
                ('IsTeacher', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Teacher_set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=30)),
                ('Last_Name', models.CharField(blank=True, max_length=30)),
                ('Gender', models.CharField(blank=True, default='N', max_length=10)),
                ('Degree', models.CharField(blank=True, max_length=10)),
                ('Course', models.CharField(blank=True, max_length=10)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Handle', models.CharField(blank=True, max_length=50)),
                ('IsTeacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='connect.profile')),
                ('Skill_set', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, null=True, size=2), blank=True, default=list, null=True, size=5)),
                ('Contact', models.BigIntegerField(blank=True, default=0)),
                ('UpVotes', models.BigIntegerField(blank=True, default=0)),
                ('DownVotes', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
    ]
