# Generated by Django 3.2.2 on 2021-05-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Contact',
            field=models.BigIntegerField(blank=True, default=None),
        ),
    ]
