# Generated by Django 3.2.3 on 2021-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_rename_id_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='Teacher_set',
        ),
        migrations.AddField(
            model_name='skill',
            name='Teacher_set',
            field=models.ManyToManyField(to='connect.Teacher'),
        ),
    ]
