# Generated by Django 3.2.3 on 2021-05-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_auto_20210523_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Skill_set',
        ),
    ]
