# Generated by Django 3.2.3 on 2021-05-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_remove_teacher_skill_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DownVotes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='UpVotes',
            field=models.BigIntegerField(default=0),
        ),
    ]
