# Generated by Django 3.2.3 on 2021-05-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20210523_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='DownVotes',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='UpVotes',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='confidence',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
