# Generated by Django 3.2.3 on 2021-05-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20210525_0412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
