# Generated by Django 3.2.3 on 2021-05-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_delete_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-confidence', '-UpVotes', 'DownVotes']},
        ),
    ]
