# Generated by Django 3.2.3 on 2021-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='Teacher_set',
            field=models.ManyToManyField(related_name='skills', to='connect.Teacher'),
        ),
    ]
