# Generated by Django 3.2.3 on 2021-05-26 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0010_auto_20210526_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.OneToOneField(db_column='email', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='auth.user', to_field='email'),
            preserve_default=False,
        ),
    ]
