# Generated by Django 3.2.3 on 2021-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0011_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Gitname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
