# Generated by Django 3.2.3 on 2021-05-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_auto_20210526_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Handle',
            new_name='handle',
        ),
    ]
