# Generated by Django 3.2.3 on 2021-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0016_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
