# Generated by Django 3.2.3 on 2021-05-29 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0017_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Contact',
            field=models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DownVotes',
            field=models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='UpVotes',
            field=models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
