# Generated by Django 3.2.3 on 2021-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0019_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='Teacher_set',
            field=models.ManyToManyField(blank=True, related_name='skills', to='connect.Teacher'),
        ),
    ]
