# Generated by Django 3.2.4 on 2021-06-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0020_alter_skill_teacher_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='IsTeacher',
        ),
    ]
