# Generated by Django 3.2.4 on 2021-06-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0021_remove_profile_isteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvals', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.skill')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='Teacher_set',
            field=models.ManyToManyField(blank=True, related_name='skills', through='connect.SkillSet', to='connect.Teacher'),
        ),
    ]
