# Generated by Django 3.2.4 on 2021-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0022_auto_20210604_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='Teacher_set',
            field=models.ManyToManyField(blank=True, related_name='skills', through='connect.SkillSet', to='connect.Teacher'),
        ),
    ]
