# Generated by Django 3.2.4 on 2021-06-07 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0024_alter_skillset_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Created',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
