# Generated by Django 3.2.6 on 2021-09-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0025_auto_20210607_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
