# Generated by Django 3.2.10 on 2021-12-26 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0029_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                       to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
