version: '3.8'

services:
  uwsgi:
    build:
      context: ..
      dockerfile: ./Dockerfile
    volumes:
      - ../:/opt/deploy/collabamigo
    environment:
      - DEBUG=True
      - DJANGO_TEST_SERVER=True
#
#  celery_worker_default:
#    volumes:
#      - ../:/opt/deploy/bezen
