# Generated by Django 3.2.4 on 2021-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
