# Generated by Django 3.2.6 on 2021-08-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0025_auto_20210607_1515'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Entries',
            new_name='Entry',
        ),
    ]
