# Generated by Django 3.2.5 on 2021-08-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_club_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice',
            field=models.CharField(default='null', max_length=5000),
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='club.choices'),
        ),
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.AddField(
            model_name='response',
            name='response',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='club.answer'),
        ),
    ]
