# Generated by Django 3.2.6 on 2021-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_competition_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.CharField(max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
