# Generated by Django 3.2.6 on 2021-09-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='form',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='form',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.RemoveField(
            model_name='social',
            name='club',
        ),
        migrations.RemoveField(
            model_name='club',
            name='link',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='on_going',
        ),
        migrations.AddField(
            model_name='club',
            name='discord',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='other',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='competition',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='competition',
            name='club',
        ),
        migrations.AddField(
            model_name='competition',
            name='club',
            field=models.ManyToManyField(related_name='competitions', to='club.Club'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(blank=True, default='', max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
