# Generated by Django 3.2.6 on 2021-09-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20210917_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='on_going',
            field=models.BooleanField(default=True),
        ),
    ]
