# Generated by Django 3.2.6 on 2021-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_competition_on_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='username',
            field=models.CharField(default='old', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
