# Generated by Django 3.2.9 on 2021-11-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_club_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='memberSize',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='club',
            name='tagline',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=100)),
                ('announcements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='club.club')),
            ],
        ),
    ]
