# Generated by Django 3.2.9 on 2021-11-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20211112_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
    ]
