# Generated by Django 3.2.9 on 2021-11-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_rename_announcements_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcements',
            new_name='club',
        ),
    ]
