# Generated by Django 3.2.9 on 2021-11-14 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_rename_announcements_announcement_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
