# Generated by Django 3.2.9 on 2021-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20211114_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='club',
            field=models.ManyToManyField(related_name='competition', to='club.Club'),
        ),
    ]
