# Generated by Django 3.2.9 on 2021-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_alter_competition_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='club',
            field=models.ManyToManyField(related_name='competitions', to='club.Club'),
        ),
    ]
