# Generated by Django 3.2.9 on 2021-11-30 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_alter_competition_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='club',
            new_name='clubs',
        ),
        migrations.AddField(
            model_name='competition',
            name='event_end',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='event_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='faq',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='competition',
            name='image_links',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='competition',
            name='link',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
