# Generated by Django 3.2.9 on 2021-12-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_auto_20211130_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='location',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
