# Generated by Django 3.2.9 on 2021-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_competition_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='event_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='event_start',
            field=models.DateTimeField(),
        ),
    ]
