# Generated by Django 3.2.9 on 2021-12-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_auto_20211202_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='faq',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
