# Generated by Django 3.2.9 on 2021-12-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_alter_competition_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='on_going',
        ),
        migrations.AlterField(
            model_name='competition',
            name='event_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
