# Generated by Django 3.2.9 on 2021-12-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0019_auto_20211206_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
