# Generated by Django 3.2.9 on 2021-12-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_alter_competition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='github',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='mail',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='telegram',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
