# Generated by Django 3.2.9 on 2021-12-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0022_alter_club_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-timestamp']},
        ),
    ]
