# Generated by Django 3.2.10 on 2021-12-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0023_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.TextField(blank=True),
        ),
    ]
