# Generated by Django 3.2.9 on 2021-12-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0025_auto_20211219_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='promotional_message',
            field=models.TextField(default='legacy'),
            preserve_default=False,
        ),
    ]
