# Generated by Django 3.2.9 on 2021-12-21 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0026_competition_promotional_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionWinner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('index', models.IntegerField()),
                ('position', models.CharField(blank=True, max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitionsWon', to='club.competition')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='winners',
            field=models.ManyToManyField(related_name='competitionsWon', through='club.CompetitionWinner', to=settings.AUTH_USER_MODEL),
        ),
    ]
