# Generated by Django 3.2.9 on 2021-12-21 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0027_auto_20211221_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionwinner',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.competition'),
        ),
        migrations.AlterField(
            model_name='competitionwinner',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionsWon', to=settings.AUTH_USER_MODEL),
        ),
    ]
