# Generated by Django 3.2.9 on 2021-12-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0028_auto_20211221_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionwinner',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
