# Generated by Django 3.2.10 on 2021-12-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0030_rename_picture_club_image_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='link',
            field=models.TextField(default='', max_length=100),
        ),
    ]
