# Generated by Django 3.2.10 on 2022-01-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0032_alter_competition_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='faq',
            field=models.TextField(default='[]', max_length=3000),
        ),
    ]
