# Generated by Django 3.2.10 on 2022-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0034_competition_graph_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
