# Generated by Django 3.2.10 on 2022-01-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0036_alter_competition_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='memberSize',
            field=models.IntegerField(default=0),
        ),
    ]
