# Generated by Django 3.2.10 on 2022-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0037_alter_club_membersize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='link',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
