# Generated by Django 3.2.10 on 2022-01-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_alter_competition_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-priority', 'event_start', 'form__closes_at', 'form__opens_at']},
        ),
        migrations.AddField(
            model_name='competition',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
