# Generated by Django 3.2.10 on 2022-01-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0040_auto_20220121_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='youtube',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
