name: Deploy main to production Heroku
'on':
  push:
    branches:
      - main
jobs:
  Internal-deploy:
    runs-on: iiit-vm
    steps:

      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Checking out main branch
        run: git checkout main && git pull

      - name: Adding remote
        run: git remote add production dokku@192.168.1.229:django-collabconnect || echo "Remote already exists"

      - name: Pushing
        run: git push production -f main:main

