name: Deploy main to Heroku-1 and Heroku-2
'on':
  push:
    branches:
      - main
jobs:
  Deploy-to-Heroku:
    runs-on: self-hosted
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Cloning the repository
        run: cd ${{ github.workspace }}/../ && (rm * -rf || echo) && eval `ssh-agent -s` && ssh-add ~/.ssh/heroku-1 && git clone git@github.com:${{ github.repository }}
      - name: Checking out main branch
        run: cd ${{ github.workspace }} && git checkout main
      - name: Set global git config
        run: git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/
      - name: Pushing to Heroku-1
        run:  cd ${{ github.workspace }} && eval `ssh-agent -s` && ssh-add ~/.ssh/heroku-1 && git remote add heroku https://git.heroku.com/mysterious-savannah-09391.git && git push heroku-1
      - name: Pushing to Heroku-2
        run: cd ${{ github.workspace }} && eval `ssh-agent -s` && ssh-add ~/.ssh/heroku-2 && git remote add heroku-2 https://git.heroku.com/serene-depths-77048.git && git push heroku-2
      - run: echo " This job's status is ${{ job.status }}."
