name: Deploy main to production Heroku
'on':
  push:
    branches:
      - main
jobs:

  Deploy-main-to-Heroku:
    runs-on: self-hosted
    steps:
      - name: Adding local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checking out main branch
        run: git checkout main

      - name: Installing pip packages
        run: pip3 install bandit pipenv flake8

      - name: Running bandit tests
        run: poetry run bandit -r ${{ github.workspace }}

      - name: Running flake8 tests
        run: poetry run flake8 ${{ github.workspace }} --exclude=migrations

      - name: Creating environment variables
        run: echo "SECRET_KEY=a">.env && echo "EMAIL=a">>.env && echo "DEVELOPMENT=True">>.env

      - name: Setting git credentials
        run: git config --global user.email "watsonhex@gmail.com" && git config --global user.name "Github runner"

      - name: Run makemigrations
        run: yes | poetry run python manage.py makemigrations

      - name: Creating requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Git add and commit
        run: git add . && if [[ $(git status -s) ]]; then git commit -m "Migrations"; fi

      - name: Heroku deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP_PRODUCTION }}
        run: dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
        shell: bash -ieo pipefail {0}

      - name: Pushing to Github
        run: git pull && git push
