name: Deploy testing to Heroku-dev
'on':
  push:
    branches:
      - testing
jobs:

  Deploy-testing-to-Heroku:
    runs-on: shikhar-debian
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Checking out testing branch
        run: git checkout testing

      - name: Installing pip packages
        run: pip3 install bandit pipenv flake8

      - name: Running bandit tests
        run:  PATH=$PATH:/home/codein2/.local/bin && bandit -r ${{ github.workspace }}

      - name: Running flake8 tests
        run: PATH=$PATH:/home/codein2/.local/bin && flake8 ${{ github.workspace }} --exclude=migrations

      - name: Creating pipenv environment
        run: PATH=$PATH:/home/codein2/.local/bin && cd ${{ github.workspace }} &&
              pipenv install && echo "SECRET_KEY=a">.env && echo "EMAIL=a">>.env

      - name: Setting git credentials
        run: git config --global user.email "watsonhex@gmail.com" && git config --global user.name "Github runner"

      - name: Run makemigrations
        run: PATH=$PATH:/home/codein2/.local/bin && yes | pipenv run python manage.py makemigrations

      - name: Git add and commit
        run: git add . && if [[ $(git status -s) ]]; then git commit -m "Migrations"; fi

      - name: Set global git config
        run: git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/

      - name: Pushing to Heroku-dev
        run:  cd ${{ github.workspace }} && eval `ssh-agent -s` && ssh-add ~/.ssh/heroku-dev &&
                (git remote add heroku-dev https://git.heroku.com/blooming-peak-53825.git ||
                  echo "Remote heroku-dev already exists" ) &&
                    git push heroku-dev -f testing:main

      - name: Pushing to Github
        run: git pull && git push

  Create-issues-using-TODO:
    runs-on: shikhar-debian
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - name: Checking out testing branch
        run: git checkout testing

      - name: Github login
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Creating issues
        run: readarray -t array <<< $(git diff HEAD^ --name-only -G "TODO" -- ':!:*.yml' | xargs --no-run-if-empty git
                grep -n "TODO" --) && for command in "${array[@]}"; do
                    gh issue create --title "${command##*#}" --body "${command}" --label "todo" || echo "ERROR $(command)";
                      done

      - name: Github logout
        run: gh auth logout --hostname github.com

  Internal-deploy:
    runs-on: iiit-vm
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Clone
        run: cd django-collabconnect

      - name: Checking out testing branch
        run: git checkout testing

      - name: Adding remote
        run: git remote add production dokku@192.168.1.229:django-collabconnect

      - name: Pushing
        run: git push production

