name: Deploy main to production Heroku
'on':
  push:
    branches:
      - main
jobs:

  Deploy-main-to-Heroku:
    runs-on: iiit-vm
    environment: production
    steps:

      - uses: actions/checkout@v2

      #      Needed when running on a new machine for the first time
      #      - name: Install system dependencies
      #        run: yes | sudo apt-get install libpq-dev python3-wheel gcc

      - name: Installing poetry
        run: which poetry || curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

      - name: Installing pip packages
        run: poetry install

      - name: Running bandit tests
        run:  PATH=$PATH:/home/codein2/.local/bin && bandit -r ${{ github.workspace }}

      - name: Running flake8 tests
        run: PATH=$PATH:/home/codein2/.local/bin && flake8 ${{ github.workspace }} --exclude=migrations

      - name: Creating pipenv environment
        run: PATH=$PATH:/home/codein2/.local/bin && cd ${{ github.workspace }} && (pipenv --rm || echo 1) &&
              pipenv install && echo "SECRET_KEY=a">.env && echo "EMAIL=a">>.env

      - name: Setting git credentials
        run: git config --global user.email "watsonhex@gmail.com" && git config --global user.name "Github runner"

      - name: Run makemigrations
        run: PATH=$PATH:/home/codein2/.local/bin && yes | pipenv run python manage.py makemigrations

      - name: Git add and commit
        run: git add . && if [[ $(git status -s) ]]; then git commit -m "Migrations"; fi

      - name: Set global git config
        run: git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/

      - name: Pushing to Heroku-main
        run:  cd ${{ github.workspace }} && eval `ssh-agent -s` && ssh-add ~/.ssh/heroku-1 &&
                (git remote add heroku https://git.heroku.com/mysterious-savannah-09391.git ||
          echo "Remote heroku-dev already exists" ) && git push -f heroku

      - name: Pushing to Github
        run: git pull && git push
