name: Deploy testing to Heroku-dev
'on':
  push:
    branches:
      - testing
jobs:
  Deploy-testing-to-Heroku:
    runs-on: self-hosted
    steps:
      - name: Cloning the repository
        run: cd ${{ github.workspace }}/../ && (rm * -rf || echo) && eval `ssh-agent -s` && ssh-add ~/.ssh/heroku-1 && git clone git@github.com:${{ github.repository }}

      - name: Checking out testing branch
        run: cd ${{ github.workspace }} && git checkout testing

      - name: Installing bandit
        run: pip3 install bandit pipenv

      - name: Running bandit tests
        run:  PATH=$PATH:/home/codein2/.local/bin && bandit -r ${{ github.workspace }}

      - name: Installing packages using pipenv
        run: PATH=$PATH:/home/codein2/.local/bin && cd ${{ github.workspace }} && pipenv install && pipenv clean && pipenv run manage.py makemigrations --noinput

      - name: Set global git config
        run: git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/

      - name: Pushing to Heroku-dev
        run:  cd ${{ github.workspace }} && eval `ssh-agent -s` && ssh-add ~/.ssh/heroku-dev && git remote add heroku-dev https://git.heroku.com/blooming-peak-53825.git && git push heroku-dev testing:main
