name: Deploy to Heroku
on: [push]
jobs:
  Deploy-to-Heroku:
    runs-on: self-hosted
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: cd ${{ github.workspace }}/../ && eval `ssh-agent -s` && ssh-add ~/.ssh/heroku && git clone git@github.com:${{ github.repository }}
      - name: List files in the repository
        run: |
          cd ${{ github.workspace }} && (git remote rm heroku|| echo) && git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/ && git remote add heroku https://git.heroku.com/mysterious-savannah-09391.git && git push heroku
      - run: echo " This job's status is ${{ job.status }}."
